version: "3"

services:
  api:
    build: ./api
    restart: always
    expose:
      - 5000
    ports: 
      - "5000:5000"
    volumes:
      - ./api:/user/src/app/api
    env_file: 
      - ./api/.env
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: 
      - ./api/.env
    expose: 
      - 5432
    ports: 
      - "5432:5432"

volumes:
  pg_data: