version: "3"

services:
  api:
    build: ./api
    env_file: 
      - ./api/.env
    volumes:
      - ./api:/user/src/app/
    expose: 
      - 5000
    ports: 
      - 5000:5000
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    # env_file: 
    #   - ./api/.env
    # expose: 
    #   - 5432
    # ports: 
    #   - 5432:5432
    # environment: 
    #   - POSTGRES_USER=$DB_USER
    #   - POSTGRES_PASSWORD=$DB_PASSWORD
    #   - POSTGRES_DB=$DB

volumes:
  pg_data: